# Generated by Django 5.0.6 on 2024-06-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadaca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
